"""Product catalog — single source of truth for all financial products."""

PRODUCTS = [
    {
        "slug": "m-shwari", "name": "M-Shwari", "category": "Savings & Loans",
        "icon": "bi-wallet2", "tagline": "Save & borrow instantly via M-PESA",
        "description": "Mobile savings and micro-loan facility with instant access.",
        "benefits": ["No paperwork", "Instant disbursement", "Build a savings record"],
        "requirements": ["Active M-PESA line", "National ID", "Registered SIM"],
        "interest": "From 7.5% flat", "repayment": "30 days", "image": "product-savings.jpg",
    },
    {
        "slug": "fuliza", "name": "Fuliza M-PESA", "category": "Savings & Loans",
        "icon": "bi-lightning-charge", "tagline": "Overdraft facility on M-PESA",
        "description": "Complete transactions even with insufficient balance.",
        "benefits": ["Automatic overdraft", "Pay on next deposit", "Flexible limits"],
        "requirements": ["M-PESA overdraft enabled", "National ID"],
        "interest": "Daily rate on usage", "repayment": "Flexible", "image": "product-savings.jpg",
    },
    {
        "slug": "kcb-mpesa", "name": "KCB M-PESA", "category": "Savings & Loans",
        "icon": "bi-bank", "tagline": "Bank-level loans on your phone",
        "description": "Access KCB credit products directly through M-PESA.",
        "benefits": ["Up to KES 1,000,000", "24/7 access", "Multiple tenors"],
        "requirements": ["National ID", "M-PESA line", "KYC completed"],
        "interest": "From 8.5% p.m.", "repayment": "1 - 6 months", "image": "product-savings.jpg",
    },
    {
        "slug": "hustler-fund", "name": "Hustler Fund", "category": "Savings & Loans",
        "icon": "bi-rocket-takeoff", "tagline": "Affordable credit for hustlers",
        "description": "Government-backed affordable micro-credit for individuals and groups.",
        "benefits": ["Low interest", "Group borrowing", "Build credit history"],
        "requirements": ["National ID", "Phone number", "Must be 18+"],
        "interest": "8% p.a. reducing", "repayment": "14 - 30 days", "image": "product-savings.jpg",
    },
    {
        "slug": "mcoop-cash", "name": "M-Coop Cash", "category": "Savings & Loans",
        "icon": "bi-people", "tagline": "Co-operative banking on mobile",
        "description": "Co-op Bank's mobile channel for savings, loans and transfers.",
        "benefits": ["Loan eligibility from savings", "Instant transfers", "Sacco integration"],
        "requirements": ["Co-op Bank account", "National ID"],
        "interest": "From 12.5% p.a.", "repayment": "Up to 12 months", "image": "product-savings.jpg",
    },
    {
        "slug": "ziidi", "name": "Ziidi Money Market Fund", "category": "Investments",
        "icon": "bi-graph-up-arrow", "tagline": "Grow your money daily",
        "description": "Low-risk money market fund with daily interest accrual.",
        "benefits": ["Daily returns", "Withdraw anytime", "No lock-in period"],
        "requirements": ["National ID", "KYC", "Min. KES 100"],
        "interest": "~10% p.a. projected", "repayment": "Liquid", "image": "product-invest.jpg",
    },
    {
        "slug": "emergency-loan", "name": "Emergency Loan", "category": "Additional Services",
        "icon": "bi-heart-pulse", "tagline": "Cash when you need it most",
        "description": "Fast cash for medical and urgent family emergencies.",
        "benefits": ["Disbursed in minutes", "Minimal documents", "Repeat borrowing"],
        "requirements": ["National ID", "Active phone", "6 months usage"],
        "interest": "From 10% flat", "repayment": "30 days", "image": "product-emergency.jpg",
    },
    {
        "slug": "salary-advance", "name": "Salary Advance", "category": "Additional Services",
        "icon": "bi-cash-coin", "tagline": "Access earned salary early",
        "description": "Advance against your salary before payday at low fees.",
        "benefits": ["Up to 50% of salary", "Deducted on payday", "No collateral"],
        "requirements": ["Employer letter", "3 payslips", "Bank account"],
        "interest": "From 5% flat", "repayment": "Next payday", "image": "product-salary.jpg",
    },
    {
        "slug": "school-fees-loan", "name": "School Fees Loan", "category": "Additional Services",
        "icon": "bi-mortarboard", "tagline": "Education never waits",
        "description": "Pay school fees in full, repay in comfortable instalments.",
        "benefits": ["Direct to school", "Flexible terms", "Holiday grace period"],
        "requirements": ["Admission letter", "Fee structure", "Parent/Guardian ID"],
        "interest": "From 9% p.m.", "repayment": "3 - 9 months", "image": "product-school.jpg",
    },
    {
        "slug": "sme-loan", "name": "SME Loan", "category": "Additional Services",
        "icon": "bi-shop", "tagline": "Grow your business",
        "description": "Working capital and asset finance for small businesses.",
        "benefits": ["Up to KES 5,000,000", "Asset financing", "Business advisory"],
        "requirements": ["Business registration", "6 months statements", "Collateral for large loans"],
        "interest": "From 13% p.a.", "repayment": "6 - 36 months", "image": "product-sme.jpg",
    },
    {
        "slug": "business-loan", "name": "Business Loan", "category": "Additional Services",
        "icon": "bi-briefcase", "tagline": "Scale with confidence",
        "description": "Expansion capital for established businesses with track record.",
        "benefits": ["Large limits", "Long tenors", "Interest-only options"],
        "requirements": ["2 years operations", "Financial statements", "Directors' IDs"],
        "interest": "From 12% p.a.", "repayment": "12 - 60 months", "image": "product-business.jpg",
    },
    {
        "slug": "agricultural-loan", "name": "Agricultural Loan", "category": "Additional Services",
        "icon": "bi-flower1", "tagline": "Finance your harvest",
        "description": "Inputs, equipment and farm expansion financing.",
        "benefits": ["Season-aligned repayments", "Equipment leasing", "Input financing"],
        "requirements": ["Farm details", "Title deed or lease", "Farm plan"],
        "interest": "From 10% p.a.", "repayment": "Up to 24 months", "image": "product-agri.jpg",
    },
    {
        "slug": "women-enterprise-loan", "name": "Women Enterprise Loan", "category": "Additional Services",
        "icon": "bi-people", "tagline": "Empowering women entrepreneurs",
        "description": "Affordable credit with mentorship for women-owned businesses.",
        "benefits": ["Lower rates", "Mentorship", "Group lending options"],
        "requirements": ["Business plan", "National ID", "Group or individual"],
        "interest": "From 8% p.a.", "repayment": "3 - 24 months", "image": "product-women.jpg",
    },
    {
        "slug": "youth-enterprise-loan", "name": "Youth Enterprise Loan", "category": "Additional Services",
        "icon": "bi-lightning", "tagline": "Fuel young ambition",
        "description": "Start-up capital and skills support for young entrepreneurs (18-35).",
        "benefits": ["Start-up friendly", "Business training", "Flexible collateral"],
        "requirements": ["Age 18-35", "Business idea/plan", "National ID"],
        "interest": "From 8% p.a.", "repayment": "3 - 18 months", "image": "product-youth.jpg",
    },
    {
        "slug": "group-loan", "name": "Group Loan", "category": "Additional Services",
        "icon": "bi-people-fill", "tagline": "Borrow together, grow together",
        "description": "Joint liability borrowing for chamas, SACCOs and community groups.",
        "benefits": ["Higher combined limits", "Shared responsibility", "Group incentives"],
        "requirements": ["3-10 members", "Group constitution", "All member IDs"],
        "interest": "From 9% p.a.", "repayment": "6 - 36 months", "image": "product-group.jpg",
    },
]